package de.bogenliga.application.business.sportjahr.api.types;

import java.time.OffsetDateTime;
import java.util.Objects;
import de.bogenliga.application.common.component.types.CommonDataObject;
import de.bogenliga.application.common.component.types.DataObject;

/**
 * Contains the values of the sportjahr business entity.
 *
 * @author Marcel Schneider
 */
public class SportjahrDO extends CommonDataObject implements DataObject {


    private static final long serialVersionUID = -3541537678685603149L;
    private Long id;
    private String name;

    private String ligaName;
    private String regionName;
    private String ligaUebergeordnetName;
    private String verantwortlichEmail;


    public SportjahrDO(final Long id, final String name, final String ligaName, final String regionName,
                       final String ligaUebergeordnetName, final String verantwortlichEmail,
                       final OffsetDateTime createdAtUtc, final Long createdByUserId, final Long version) {
        this.id = id;
        this.name = name;
        this.ligaName = ligaName;
        this.regionName = regionName;
        this.ligaUebergeordnetName = ligaUebergeordnetName;
        this.verantwortlichEmail = verantwortlichEmail;

        this.createdAtUtc = createdAtUtc;
        this.createdByUserId = createdByUserId;
        this.version = version;

    }


    /**
     * Constructor with optional parameters
     *
     * @param id
     */
    public SportjahrDO(final Long id, final String ligaName, final String regionName,
                       final String ligaUebergeordnetName, final String verantwortlichEmail,
                       final OffsetDateTime createdAtUtc, final Long createdByUserId, final Long version,
                       final OffsetDateTime lastModifiedAtUtc, final Long lastModifiedByUserId) {
        this.id = id;
        this.ligaName = ligaName;
        this.regionName = regionName;
        this.ligaUebergeordnetName = ligaUebergeordnetName;
        this.verantwortlichEmail = verantwortlichEmail;

        this.createdAtUtc = createdAtUtc;
        this.createdByUserId = createdByUserId;
        this.version = version;
        this.lastModifiedAtUtc = lastModifiedAtUtc;
        this.lastModifiedByUserId = lastModifiedByUserId;


    }


    /**
     * Constructor with id for deleting existing entries
     *
     * @param id
     */
    public SportjahrDO(final Long id) {
        this.id = id;
    }


    /* Autogenerated getter and setters */


    public Long getId() {
        return id;
    }


    public void setId(final Long id) {
        this.id = id;
    }


    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    @Override
    public int hashCode() {
        return Objects.hash(id, name,
                createdByUserId, lastModifiedAtUtc,
                lastModifiedByUserId, version);
    }


    @Override
    public boolean equals(final Object o) {
        if (o instanceof SportjahrDO) {
            final SportjahrDO that = (SportjahrDO) o;
            return (Objects.equals(getId(), that.getId()) &&
                    Objects.equals(getName(), that.getName()));
        }
        return false;

    }

}
