INSERT INTO recht(
recht_id,
recht_name
)
VALUES
       (21,'CAN_READ_DSBMITGLIEDER'),
       (22,'CAN_CREATE_DSBMITGLIEDER'),
       (23,'CAN_MODIFY_DSBMITGLIEDER'),
       (24,'CAN_DELETE_DSBMITGLIEDER'),
       (25, 'CAN_CREATE_MANNSCHAFT'),
       (26, 'CAN_CREATE_VEREIN_DSBMITGLIEDER'),
       (27, 'CAN_MODIFY_VEREIN_DSBMITGLIEDER')
;