package de.bogenliga.application.business.schusszettel.api;

import de.bogenliga.application.business.schusszettel.api.types.SatzEingabeDO;
import de.bogenliga.application.business.schusszettel.api.types.SchuetzenMeldungDO;
import de.bogenliga.application.business.schusszettel.api.types.TabletSchusszettelDO;
import de.bogenliga.application.common.errorhandling.exception.BusinessException;

/**
 * interface for tablet-based archery score entry operations
 * 
 * <h2>FUNCTIONALITY</h2>
 * Provides API for tablet applications to manage archery competition score entry
 * using token-based authentication. Implements state machine workflow for shooter
 * registration and score submission.
 * 
 * <h2>OPERATION TYPES</h2>
 * <ul>
 *   <li>GET: Retrieve current session state and context data</li>
 *   <li>POST: Submit shooter registrations or arrow scores</li>
 * </ul>
 * 
 * <h2>AUTHENTICATION</h2>
 * All operations require valid token generated by TabletSchusszettelAdminComponent.
 * Invalid tokens result in NOT_ALLOWED status.
 * 
 * @see TabletSchusszettelAdminComponent Session management and token generation
 * @see TabletSchusszettelDO Response data structure
 */
public interface TabletSchusszettelComponent {

    /**
     * Retrieves current session state and context data for tablet display.
     * 
     * Validates access token and evaluates current state. For WARTE state,
     * evaluates with opponent session for potential state advancement.
     * Returns state-specific data including available shooters, current scores,
     * or match results.
     * 
     * @param wettkampfid Competition identifier
     * @param teamid Team identifier  
     * @param token Access token for session authentication
     * @return TabletSchusszettelDO containing current state and context data
     */
    TabletSchusszettelDO getStatus(long wettkampfid, long teamid, String token);

    /**
     * Submits arrow scores for current pass.
     * 
     * Validates session state is SATZEINGABE and exactly 3 shooters provided.
     * Updates pass entries with arrow scores (0-10 points). Transitions state
     * to WARTE and evaluates with opponent for next state.
     * 
     * @param wettkampfid Competition identifier
     * @param teamid Team identifier
     * @param token Access token for session authentication
     * @param doObj Score data for 3 shooters
     * @throws BusinessException if validation fails or invalid state
     */
    void submitSatz(long wettkampfid, long teamid, String token, SatzEingabeDO doObj);

    /**
     * Registers shooters for current pass.
     * 
     * Validates session state is SCHUETZENMELDUNG and exactly 3 shooters provided.
     * Validates shooters are deployed team members (eingesetzt ≥ 1) with no duplicates.
     * Creates placeholder pass entries for all 5 sets. Transitions state to SATZEINGABE.
     * 
     * @param wettkampfid Competition identifier
     * @param teamid Team identifier
     * @param token Access token for session authentication
     * @param doObj Shooter registration data for 3 shooters
     * @throws BusinessException if validation fails or invalid state
     */
    void submitSchuetzen(long wettkampfid, long teamid, String token, SchuetzenMeldungDO doObj);

    /**
     * Checks whether the given token is a valid, currently active session token
     * for the given wettkampf/team combination.
     *
     * Used to grant read-only access to other endpoints (e.g. match details)
     * to anonymous QR-scanning clients, without requiring a login.
     *
     * @param wettkampfid Competition identifier
     * @param teamid Team identifier
     * @param token Access token to validate
     * @return true if the token belongs to an existing session for this wettkampf/team
     */
    boolean isValidToken(long wettkampfid, long teamid, String token);
}
