DO $do$
BEGIN

    --insert test data into table veranstaltung
    INSERT INTO veranstaltung (veranstaltung_id, veranstaltung_wettkampftyp_id, veranstaltung_name, veranstaltung_sportjahr, veranstaltung_meldedeadline, veranstaltung_ligaleiter_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, veranstaltung_liga_id) VALUES (1100, 1, 'SWT2_Veranstaltung', 2016, '2017-11-01', 2, '2021-01-28 20:51:23.509994', 0, null, null, 0, 1000) ON CONFLICT DO NOTHING;

    --insert test data into table wettkampf
    INSERT INTO wettkampf (wettkampf_id, wettkampf_veranstaltung_id, wettkampf_datum, wettkampf_beginn, wettkampf_tag, wettkampf_disziplin_id, wettkampf_wettkampftyp_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, wettkampfausrichter, wettkampf_strasse, wettkampf_plz, wettkampf_ortsname) VALUES (2009, 1100, '2016-05-08', '15:30', 0, 0, 0, '2021-01-28 21:27:42.305203', 0, null, null, 7, null, 'Bahnhofstrasse', 72764, 'Reutlingen') ON CONFLICT DO NOTHING;
    INSERT INTO wettkampf (wettkampf_id, wettkampf_veranstaltung_id, wettkampf_datum, wettkampf_beginn, wettkampf_tag, wettkampf_disziplin_id, wettkampf_wettkampftyp_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, wettkampfausrichter, wettkampf_strasse, wettkampf_plz, wettkampf_ortsname) VALUES (2008, 1100, '2016-05-08', '15:30', 3, 0, 0, '2021-01-28 21:27:42.305203', 0, null, null, 7, null, 'Bahnhofstrasse', 72764, 'Reutlingen') ON CONFLICT DO NOTHING;
    INSERT INTO wettkampf (wettkampf_id, wettkampf_veranstaltung_id, wettkampf_datum, wettkampf_beginn, wettkampf_tag, wettkampf_disziplin_id, wettkampf_wettkampftyp_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, wettkampfausrichter, wettkampf_strasse, wettkampf_plz, wettkampf_ortsname) VALUES (2007, 1100, '2016-05-07', '15:30', 4, 0, 0, '2021-01-28 21:27:42.305203', 0, null, null, 6, null, 'Bahnhofstrasse', 72764, 'Reutlingen') ON CONFLICT DO NOTHING;
    INSERT INTO wettkampf (wettkampf_id, wettkampf_veranstaltung_id, wettkampf_datum, wettkampf_beginn, wettkampf_tag, wettkampf_disziplin_id, wettkampf_wettkampftyp_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, wettkampfausrichter, wettkampf_strasse, wettkampf_plz, wettkampf_ortsname) VALUES (2006, 1100, '2016-05-05', '15:30', 1, 0, 0, '2021-01-28 21:27:42.305203', 0, null, null, 9, null, 'Bahnhofstrasse', 72764, 'Reutlingen') ON CONFLICT DO NOTHING;
    INSERT INTO wettkampf (wettkampf_id, wettkampf_veranstaltung_id, wettkampf_datum, wettkampf_beginn, wettkampf_tag, wettkampf_disziplin_id, wettkampf_wettkampftyp_id, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, wettkampfausrichter, wettkampf_strasse, wettkampf_plz, wettkampf_ortsname) VALUES (2005, 1100, '2016-05-06', '15:30', 2, 0, 0, '2021-01-28 21:27:42.305203', 0, null, null, 9, null, 'Bahnhofstrasse', 72764, 'Reutlingen') ON CONFLICT DO NOTHING;

    --insert test data into table match
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 3, 1029, 6, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 3, 1054) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 1, 1024, 1, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 6, 1050) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 2, 1027, 4, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 6, 1052) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 1, 1025, 2, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 5, 1051) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 3, 1028, 5, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 5, 1053) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 2, 1026, 3, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 6, 1058) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 4, 1031, 8, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 5, 1057) ON CONFLICT DO NOTHING;
    INSERT INTO match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2006, 1, 4, 1030, 7, null, null, null, null, null, null, null, '2020-03-01 17:14:35.105428', 0, null, null, 6, 1056) ON CONFLICT DO NOTHING;


END
$do$