-- Test matches for wettkampf_id=2020 to enable Schusszettel PDF download without Generiere-Matches
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 1, 1024, 1, 2, 6, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90001);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 1, 1025, 2, 0, 2, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90002);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 2, 1026, 3, 2, 6, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90003);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 2, 1027, 4, 0, 4, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90004);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 3, 1028, 5, 2, 6, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90005);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 3, 1029, 6, 0, 2, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90006);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 4, 1030, 7, 2, 7, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90007);
INSERT INTO public.match (match_wettkampf_id, match_nr, match_begegnung, match_mannschaft_id, match_scheibennummer, match_matchpunkte, match_satzpunkte, match_strafpunkte_satz_1, match_strafpunkte_satz_2, match_strafpunkte_satz_3, match_strafpunkte_satz_4, match_strafpunkte_satz_5, created_at_utc, created_by, last_modified_at_utc, last_modified_by, version, match_id) VALUES (2020, 1, 4, 1031, 8, 0, 1, null, null, null, null, null, '2024-03-23 10:00:00.000000', 0, null, null, 0, 90008);
