name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Pipeline
        uses: cypress-io/github-action@v6
