name: Cypress test pipeline
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: swt2
          POSTGRES_DB: swt2
          POSTGRES_PASSWORD: swt2
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U swt2 -d swt2"
          --health-timeout=60s
          --health-interval=15s
          --health-retries=5

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
           distribution: 'zulu'
           java-version: '17'
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
           ref: develop
           fetch-depth: 0  

      - name: Clone frontend repository
        uses: actions/checkout@v2
        with:
          repository: bettercodepaul/swt2-bsa-frontend
          ref: develop
          path: swt2-bsa-frontend

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build backend project
        working-directory: ./bogenliga
        run: |
          java -version
          export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
          mvn clean install -T 1C
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  
          
      - name: Install frontend dependencies
        working-directory: ./swt2-bsa-frontend/bogenliga
        run: |
          npm install

      - name: Build frontend
        working-directory: ./swt2-bsa-frontend/bogenliga
        run: |
          npm run build  

      - name: Start backend, frontend and run Cypress tests
        working-directory: .
        run: |
          echo "Start backend"
          mvn -f ./bogenliga/bogenliga-application/pom.xml spring-boot:run -Dspring-boot.run.jvmArguments="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED" > backend.log 2>&1 &

          echo "Start frontend"
          nohup npm --prefix ./swt2-bsa-frontend/bogenliga start  &

          echo "Wait for both to be ready"
          npx wait-on http://localhost:4200

          echo "Run Cypress tests"
          npx cypress run --browser chrome --project ./swt2-bsa-frontend/bogenliga --reporter mochawesome  --reporter-options reportDir=cypress-results,overwrite=false,html=true,json=true

          npx mochawesome-merge cypress-results/*.json > cypress-results/merged-report.json

          npx marge cypress-results/merged-report.json --reportDir cypress-results --reportFilename merged-report
          
      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: ./cypress-results
          
      - name: Tests completed
        if: success()
        run: echo "Build and tests completed successfully!"
