name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Pipeline
        uses: cypress-io/github-action@v6
